apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: import-flow-bw5
  title: Import flow for BW5 projects
  description: Import existing BW5 projects into TIBCO Developer Hub (v1729610782)
  tags:
    - import-flow
    - tibco
    - business-works-5
    - developer-hub
spec:
  owner: group:default/tibco-imported
  type: integration

  parameters:
    - title: Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: GitHub repository with Existing BusinessWorks 5 Project
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

    - title: Fill in some steps
      required:
        - application
        - owner
      properties:
        application_folder:
          title: BusinessWorks 5 Application Folder
          type: string
          description: Folder of BusinessWorks 5 Application to import
        application:
          title: BusinessWorks 5 Application
          type: string
          description: Name of the BusinessWorks 5 Application to import
        owner:
          title: Owner
          type: string
          description: Owner of the template
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  # The import flow consist out of 4 steps:
  # 1. Fetch the project from GitHub
  # 2. Generate the Component YAML
  # 3. Commit the Component YAML file back to the GitHub project branch creating a pull request
  # 4. Register the Component in the catalog

  steps:
    - id: fetch
      name: Fetch project
      action: fetch:plain
      input:
        url: ${{ "https://"  + (parameters.repoUrl | parseRepoUrl).host + "/" + (parameters.repoUrl | parseRepoUrl).owner + "/" +  (parameters.repoUrl | parseRepoUrl).repo }}

    - id: extract
      name: Extract Parameters
      action: tibco:extract-parameters
      input:
        failOnError: true
        extractParameters:
          bw5_project:
            type: xml
            filePath: ${{ parameters.application_folder + "/" + parameters.application + "/.folder"}}
            jsonPath: "$['Repository:repository'].folder"

  output:
    links:
      - title: Business Works 5 Documentation
        icon: catalog
        url: https://docs.tibco.com/products/tibco-activematrix-businessworks-5-13-0
